owner: LeastAuthority
repo: org-members-upptime

sites:
  - name: 1Password
    url: https://my.1password.com/signin
  - name: GitHub - LA
    url: https://github.com/LeastAuthority/
  - name: GitHub - PS
    url: https://github.com/PrivateStorageio/
  - name: GitLab - PS
    url: https://whetstone.private.storage/
  - name: Google Workspace
    url: https://workspace.google.com/dashboard
  - name: LimeSurvey - LA
    icon: https://raw.githubusercontent.com/LeastAuthority/org-members-upptime/master/assets/limesurvey.ico
    url: $URL_LIMESURVEY_LA
    expectedStatusCodes:
      - 200
  - name: Open Project - LA
    url: https://leastauthority.openproject.com/
  - name: Overleaf - LA
    url: https://www.overleaf.com/project/6058b9d527814c9a91678a8a
    expectedStatusCodes:
      - 403
  - name: Matomo - PS
    icon: https://raw.githubusercontent.com/LeastAuthority/org-members-upptime/master/assets/matomo-icon.png
    url: https://matomo.private.storage/
    expectedStatusCodes:
      - 200
  - name: Remote
    url: https://remote.com/
  - name: Slack - LA
    url: https://leastauthority.slack.com/
  - name: SuiteCRM - LA
    icon: https://raw.githubusercontent.com/LeastAuthority/org-members-upptime/master/assets/suitecrm.ico
    url: $URL_SUITECRM_LA
    expectedStatusCodes:
      - 200
  - name: Whereby - LA
    url: https://la.whereby.com/
  - name: WP Engine
    url: https://my.wpengine.com/
  - name: WordPress - LA
    url: https://leastauthority.com/wp-login.php
    expectedStatusCodes:
      - 200
  - name: Zulip - PS
    icon: https://raw.githubusercontent.com/LeastAuthority/org-members-upptime/master/assets/zulip-icon.svg
    url: $URL_ZULIP_PS
    expectedStatusCodes:
      - 200

status-website:
  baseUrl: /org-members-upptime
  logoUrl: https://raw.githubusercontent.com/LeastAuthority/org-members-upptime/master/assets/upptime-icon.svg
  name: Org Members
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by [GitHub](https://github.com/LeastAuthority/org-members-upptime)."
  introMessage: This site monitors the resources available to members of [Least Authority](https://leastauthority.com/)
  navbar:
    - title: End Users
      href: /end-users-upptime
    - title: Org Members
      href: /org-members-upptime
    - title: Infrastructure
      href: /infrastructure-upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
